# Generated by Django 5.2.7 on 2025-11-20 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugadores',
            fields=[
                ('idjugador', models.AutoField(primary_key=True, serialize=False)),
                ('idbanner', models.CharField(max_length=9, unique=True)),
                ('nombrejugador', models.CharField(max_length=250)),
                ('apellidojugador', models.CharField(max_length=250)),
                ('numerocamisetajugador', models.IntegerField()),
                ('posicionjugador', models.CharField(choices=[('Delantero', 'Delantero'), ('Mediocampista', 'Mediocampista'), ('Defensa', 'Defensa'), ('Portero', 'Portero')], max_length=250)),
                ('jugadoractivo', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'jugador',
            },
        ),
    ]
