# Generated by Django 5.2.7 on 2026-01-11 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugadores',
            name='idbanner',
            field=models.CharField(error_messages={'unique': 'Ya existe un jugador asociado a ese ID Banner.'}, max_length=9, unique=True),
        ),
    ]
