# Generated by Django 5.2.8 on 2026-01-08 20:52

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            "CREATE SCHEMA IF NOT EXISTS football;",
            reverse_sql="DROP SCHEMA IF EXISTS football CASCADE;",
        ),
        migrations.CreateModel(
            name='PlayerDistanceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('player_id', models.BigIntegerField(db_index=True)),
                ('match_id', models.IntegerField(db_index=True)),
                ('total_distance_km', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'football"."player_distance_history',
                'indexes': [models.Index(fields=['player_id', 'match_id'], name='player_dist_player__539887_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlayerEvents',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('player_id', models.BigIntegerField(db_index=True)),
                ('match_id', models.IntegerField(db_index=True)),
                ('event_type', models.CharField(choices=[('pass', 'Pass'), ('shot_on_target', 'Shot on target'), ('goal', 'Goal'), ('foul', 'Foul'), ('assist', 'Assist'), ('interception', 'Interception')], max_length=20)),
                ('timestamp_ms', models.BigIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'football"."player_events',
                'indexes': [models.Index(fields=['player_id', 'match_id'], name='player_even_player__072e6e_idx'), models.Index(fields=['match_id', 'event_type'], name='player_even_match_i_629e7c_idx'), models.Index(fields=['metadata'], name='idx_events_metadata_gin')],
            },
        ),
        migrations.CreateModel(
            name='PlayerHeatmaps',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('player_id', models.BigIntegerField(db_index=True)),
                ('match_id', models.IntegerField(db_index=True)),
                ('heatmap_url', models.URLField(blank=True)),
                ('resolution_w', models.PositiveIntegerField(blank=True, null=True)),
                ('resolution_h', models.PositiveIntegerField(blank=True, null=True)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('mime_type', models.TextField(default='image/png')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'football"."player_heatmaps',
                'indexes': [models.Index(fields=['player_id', 'match_id'], name='player_heat_player__de3068_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlayerStatsConsolidated',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('player_id', models.BigIntegerField(db_index=True)),
                ('match_id', models.IntegerField(db_index=True)),
                ('shirt_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('team', models.TextField(blank=True)),
                ('team_color', models.TextField(blank=True)),
                ('passes', models.PositiveIntegerField(default=0)),
                ('shots_on_target', models.PositiveIntegerField(default=0)),
                ('has_goal', models.BooleanField(default=False)),
                ('avg_speed_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('avg_possession_time_s', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('heatmap_image_path', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'football"."player_stats_consolidated',
                'indexes': [models.Index(fields=['match_id'], name='player_stat_match_i_c2ce25_idx'), models.Index(fields=['player_id', 'match_id'], name='player_stat_player__eb5b5d_idx')],
                'unique_together': {('player_id', 'match_id')},
            },
        ),
    ]
