# Generated by Django 5.2.7 on 2026-01-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerstatsconsolidated",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
