# Generated by Django 5.2.7 on 2026-01-21 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0002_playerstatsconsolidated_started_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerstatsconsolidated",
            name="player_id",
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
