# Generated by Django 5.2.7 on 2026-01-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0004_alter_playerheatmaps_player_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerdistancehistory",
            name="player_id",
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="playerevents",
            name="player_id",
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
