# Generated by Django 5.2.7 on 2026-01-21 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0005_alter_playerdistancehistory_player_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerstatsconsolidated",
            name="team",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="playerstatsconsolidated",
            name="team_color",
            field=models.TextField(blank=True, null=True),
        ),
    ]
