# Generated by Django 5.2.7 on 2026-01-21 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jugadores", "0002_alter_jugadores_idbanner"),
        ("stats", "0006_alter_playerstatsconsolidated_team_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerStatsHist",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("partidos_jugados", models.PositiveIntegerField(default=0)),
                ("total_passes", models.PositiveIntegerField(default=0)),
                ("total_shots_on_target", models.PositiveIntegerField(default=0)),
                ("total_goals", models.PositiveIntegerField(default=0)),
                (
                    "total_distance_km",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "total_possession_time_s",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "avg_speed_global_kmh",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "jugador",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estadisticas_generales",
                        to="jugadores.jugadores",
                    ),
                ),
            ],
            options={
                "db_table": 'football"."player_stats_hist',
            },
        ),
        migrations.DeleteModel(
            name="PlayerDistanceHistory",
        ),
        migrations.DeleteModel(
            name="PlayerEvents",
        ),
        migrations.DeleteModel(
            name="PlayerHeatmaps",
        ),
        migrations.AlterField(
            model_name="playerstatsconsolidated",
            name="player_id",
            field=models.BigIntegerField(db_index=True),
        ),
    ]
