# Generated by Django 5.2.7 on 2026-01-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0007_playerstatshist_delete_playerdistancehistory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerstatsconsolidated",
            name="goals",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
