# Generated by Django 5.2.7 on 2026-07-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0008_playerstatsconsolidated_goals"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playerstatsconsolidated",
            name="has_goal",
        ),
        migrations.RemoveField(
            model_name="playerstatsconsolidated",
            name="shots_on_target",
        ),
        migrations.AddField(
            model_name="playerstatsconsolidated",
            name="movement_trajectories_path",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="playerstatsconsolidated",
            name="player_crop_path",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="playerstatsconsolidated",
            name="team_heatmap_path",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="playerstatsconsolidated",
            name="match_id",
            field=models.BigIntegerField(db_index=True),
        ),
    ]
