# Generated by Django 5.2.7 on 2026-07-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0009_remove_playerstatsconsolidated_has_goal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerstatsconsolidated",
            name="avg_possession_time_s",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="playerstatsconsolidated",
            name="avg_speed_kmh",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="playerstatsconsolidated",
            name="distance_km",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
    ]
