# Generated by Django 5.2.7 on 2026-07-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0010_alter_playerstatsconsolidated_avg_possession_time_s_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerstatsconsolidated",
            name="avg_possession_time_s",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="playerstatsconsolidated",
            name="avg_speed_kmh",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="playerstatsconsolidated",
            name="distance_km",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=12, null=True
            ),
        ),
    ]
