# Generated by Django 5.2.7 on 2026-07-12 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0011_alter_playerstatsconsolidated_avg_possession_time_s_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="playerstatsconsolidated",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="playerstatsconsolidated",
            name="avg_acceleration",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=12, null=True
            ),
        ),
    ]
