# Generated by Django 5.2.7 on 2026-07-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0012_alter_playerstatsconsolidated_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerstatsconsolidated",
            name="team_goals",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
