# Generated by Django 5.2.7 on 2026-07-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "stats",
            "0014_playerstatsconsolidated_player_movement_trajectories_path_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="playerstatsconsolidated",
            name="voronoi_territories_path",
            field=models.URLField(blank=True),
        ),
    ]
