# Generated by Django 5.2.7 on 2026-07-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0015_playerstatsconsolidated_voronoi_territories_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerstatsconsolidated",
            name="player_id",
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
